apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://192.168.72.4:31238

  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: Ov23lifG7a0TuMOlvQXI
          clientSecret: 6efbf0bc1093f64cdf143fdb8f304f252405ece5
        redirectURI: https://192.168.72.4:31238/api/dex/callback
